# Generated by Django 3.2 on 2024-01-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
