# Generated by Django 3.2 on 2024-01-28 00:26

from django.db import migrations, models
import reviews.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.utils.current_year], verbose_name='Год выпуска'),
        ),
    ]
